import { useState } from 'react'

interface ResultsDisplayProps {
  results: {
    prd: string
    userStories: string
    functionalRequirements: string
    uiWireframes: string
  }
}

type TabType = 'prd' | 'userStories' | 'functionalRequirements' | 'uiWireframes'

export default function ResultsDisplay({ results }: ResultsDisplayProps) {
  const [activeTab, setActiveTab] = useState<TabType>('prd')

  const tabs: { id: TabType; label: string; icon: string }[] = [
    { id: 'prd', label: 'PRD', icon: '📋' },
    { id: 'userStories', label: 'User Stories', icon: '👥' },
    { id: 'functionalRequirements', label: 'Functional Req.', icon: '⚙️' },
    { id: 'uiWireframes', label: 'UI/UX Design', icon: '🎨' },
  ]

  const handleDownload = (type: TabType) => {
    const content = results[type]
    const element = document.createElement('a')
    const file = new Blob([content], { type: 'text/plain' })
    element.href = URL.createObjectURL(file)
    element.download = `${type}-${new Date().toISOString().split('T')[0]}.txt`
    document.body.appendChild(element)
    element.click()
    document.body.removeChild(element)
  }

  const handleCopy = (text: string) => {
    navigator.clipboard.writeText(text)
    alert('Copied to clipboard!')
  }

  const getContent = (tab: TabType) => {
    return results[tab]
  }

  return (
    <div className="bg-white rounded-lg shadow-lg overflow-hidden">
      {/* Tab Navigation */}
      <div className="flex flex-wrap border-b border-gray-200 bg-gray-50">
        {tabs.map((tab) => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            className={`flex-1 px-4 py-4 text-sm font-medium transition ${
              activeTab === tab.id
                ? 'border-b-2 border-blue-600 text-blue-600 bg-white'
                : 'text-gray-600 hover:text-gray-900'
            }`}
          >
            <span className="hidden sm:inline">{tab.icon} </span>
            {tab.label}
          </button>
        ))}
      </div>

      {/* Content */}
      <div className="p-6">
        <div className="mb-4 flex gap-2">
          <button
            onClick={() => handleDownload(activeTab)}
            className="flex items-center gap-2 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition text-sm"
          >
            📥 Download
          </button>
          <button
            onClick={() => handleCopy(getContent(activeTab))}
            className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition text-sm"
          >
            📋 Copy
          </button>
        </div>

        <div className="bg-gray-50 rounded-lg p-4 max-h-96 overflow-y-auto">
          <pre className="text-sm text-gray-800 whitespace-pre-wrap font-sans">
            {getContent(activeTab)}
          </pre>
        </div>

        <p className="text-xs text-gray-500 mt-4">
          💡 All outputs are generated by AI and should be reviewed and edited before final use.
        </p>
      </div>
    </div>
  )
}
